services:
  db:
    image: postgres:15
    container_name: datasphere_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datasphere
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_network

  api:
    build: .
    container_name: data_ai_api
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - searxng
    volumes:
      - ./storage:/app/storage
    shm_size: '2gb'         
    mem_limit: 8g 
    networks:
      - ai_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ai_network

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge

volumes:
  postgres_data: